apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: pushpendrad/busybox:v1
        ports:
        - containerPort: 8080
