version: 0.2

phases:
 install:
   commands:
      - echo Entered the install phase...
 pre_build:
    commands:
    - echo Entered the pre_build phase...
 build:
    commands:
      - echo Entered the build phase..
      - echo Build started on `date`
      - mvn cobertura:cobertura
 post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files:
      - target/site/cobertura/index.html
